# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - java11

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_338e44d515e24eb79726444e63064e5d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_24c82def24a748459f6e04a583f13e88 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_338e44d515e24eb79726444e63064e5d }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'java11'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e290ceac8d7e4203a86bc237abbc6761 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_338e44d515e24eb79726444e63064e5d }}/appsvc/staticsite:${{ github.sha }}'